package com.accessmirai.mc.amcore;

import net.minecraftforge.fml.common.ModMetadata;

public class AMCInfo {
    public static void loadInfo(ModMetadata meta) {
        meta.authorList.add("Sora Tonami");
        meta.autogenerated = false;
        meta.description = "Access未来が運営するマイクラ鯖のMODのうち、自社製のMODの前提MODです。";
        meta.logoFile = "assets/amcore/logo.png";
        meta.modId = AMCMain.MOD_ID;
        meta.name = AMCMain.MOD_NAME;
        meta.updateJSON = "https://projectr.ddo.jp/assets/mcmod/AMCoreVersionCheck.json";
        meta.url = "https://projectr.ddo.jp/";
        meta.version = AMCMain.VERSION;
    }
}
